### ISSUE TITLE
Move left pane of objects  to a drop down in the header

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/translations-app#17]
I wonder if it would be better to remove the left object pane, and have three drop downs in the menu

1) Locale
2) Translation status
3) List of objects to translate

What do you think @Awnage @larshelge @Markionium ?

**Comment by Markionium** [comment]
What would be the reasoning for that?

I feel like it might take away from the workflow more than it would add.
The list of objects is fairly long so i think the list might fit it better than a dropdown.

If we were short on screen real-estate then perhaps yes, so maybe for mobile, if you want to optimise it for there at all :)

**Comment by jason-p-pickering** [comment]
I am not sure really. I am not sure that people are going to be flipping back and forth between objects so often. I would imagine people translating one, and then going on to another. 

If you look at the translation server (https://translate.dhis2.org/projects/) things are organized as modules. 

![image](https://cloud.githubusercontent.com/assets/2968061/20474846/e6c73b7e-afc8-11e6-8235-cbfc3493fa31.png)

Obviously having the translated/untranslated stats would be a nice feature. :) 

Anyway, once you are in a module (thing object) , you just proceed with the translations one by one. 
I see this akin to the objects in the left side pane. 
![workspace 1_999](https://cloud.githubusercontent.com/assets/2968061/20474932/54e22060-afc9-11e6-880e-ab4892ef4b17.png)

I am just not sure its so important to even occupy that real estate. Perhaps the ability to collapse it would be nice. 

Anyway, its not too important, but I think there has been a lot of thought put into the Pootle UI to support translation, so just trying to emulate that as much as possible.

**Comment by Markionium** [comment]
Right, so in that case perhaps a landing page with the "type" of objects plus the potential translation status and then when you click on one, it'll select that one in the dropdown up top.

I don't really know, but you're probably right that there went more thought into the Pootle UI than we put into ours ;)

**Comment by jason-p-pickering** [comment]
![image](https://cloud.githubusercontent.com/assets/2968061/21379294/334f5b0c-c74d-11e6-976b-34b926a11657.png)

**Comment by jason-p-pickering** [comment]
Implemented in 35ac00488cceafae3269d40573cc34fb5c430ae0
