### ISSUE TITLE
Front text is garbled

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/translations-app#5]
![image](https://cloud.githubusercontent.com/assets/2968061/20431515/5c1fde48-ad68-11e6-8e15-46da622b862d.png)

**Comment by jason-p-pickering** [comment]
Should be fixed in 641a3370e62d9b85293e2250716d1e137fd64e72

**Comment by Markionium** [comment]
It should be noted that this will now show the same result for when the app is build as zip file that is installed as it doesn't properly work now.

This fix and https://github.com/dhis2/translations-app/commit/01cd86721a2d79b28be11543cde0fc73e696b09a make it impossible to use it as downloadable/installable app.

These issues should be addressed in core probably.
